### ISSUE TITLE
Some websites break when a Keyword ends with a special character, such as .

### ISSUE THREAD

**Issue by MKrabs** [AidanSpeakss/streamer-mode-for-firefox#4]
When a broken Keyword is entered, some sites, such as google sites, render only partially or completely [broken](https://imgur.com/a/YSpB4DO)

Keywords that I've tested with an [Imgur album](https://imgur.com/a/WqTGfmU):

- m.
- m,.
- m,,
- m
- ? * ; or any other special character
- or

**Comment by AidanSpeakss** [comment]
This happened because the text from the PII input fields was being added directly to a regex expression, without escaping special characters that regex uses. This also allowed you to use regex before it was even implemented as a feature. I've since made a separate regex field so people can now properly use regular expressions, and added a step for the non-regex field that escapes any special characters used by regex.

The fix will be in the v1.7 release.

**Comment by MKrabs** [comment]
How about an improved input area, with an option to check / uncheck "use regex" or plain text ?

Maybe this could help ? https://stackoverflow.com/questions/3561493/is-there-a-regexp-escape-function-in-javascript

**Comment by AidanSpeakss** [comment]
This is actually almost exactly what I did. The new release will have two fields one for regex and one for non-regex. And it uses that exact same function in the non-regex area to escape regex characters.

Here's a screenshot: https://imgur.com/a/xHD8YZB
